theme = "lilafarb"

[editor]
line-number = "relative"
cursorline = true
shell = ["nu", "-c"]
rulers = [80, 100]
bufferline = "multiple"
color-modes = true
text-width = 100
gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-modification-indicator", "version-control"]
center = ["file-type", "file-encoding", "file-line-ending"]
right = ["diagnostics", "workspace-diagnostics", "primary-selection-length", "selections", "position", "total-line-numbers"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "▏"

[editor.lsp]
display-inlay-hints = true
display-messages = true